### ISSUE TITLE
Deletion of leaf-list with instance doesn't have ygot strcuture populated with value

### ISSUE THREAD

**Issue by justinejose91** [project-arlo/sonic-mgmt-framework#127]
When you delete a leaf-list with instance, ygot structure for APP-module doesn't contain leaf-list data populated.

**Comment by justinejose91** [comment]
@mbalachandar Did you get a chance to look into this issue?

**Comment by jeffyin-dell** [comment]
@mbalachandar -- any update? Can't complete the VLAN feature without this.

**Comment by mbalachandar** [comment]
Hi Jeff

The ETA for this support is on coming Tuesday Oct'1 2019.

Thanks
Balachandar

**Comment by mbalachandar** [comment]
This issue is fixed and checked in. You can pull the changes

**Comment by justinejose91** [comment]
Do we have changes in master? I tested it out now, and it still doesn't have ygot structure populated with trunk Vlan value.

**Comment by mbalachandar** [comment]
Hi Justin

Its not in master, please check with Prabhu to pull the changes from broadcom branch. 

Thanks
Balachandar

**Comment by justinejose91** [comment]
@PrabhuSreenivasan Could you tell me when these changes would be available in master?

**Comment by bhavini-gada** [comment]
@PrabhuSreenivasan - Where are you merging this change ?

**Comment by jeffyin-dell** [comment]
@justinejose91 -- did the merge get done? Can we close this issue?

**Comment by sachin-brm** [comment]
@Justine.Jose@dell.com <Justine.Jose@dell.com>  Arun synced the code early
this week. I think Bala's fix would have got merged already... copying him
to check and confirm though...

Regards,


Sachin.

**Comment by justinejose91** [comment]
This is merged. @sachin-brm @jeff-yin I verified it. Closing the issue.
